### PR TITLE
Revamp Chatbox | ADD Appealing and Interactive user Features

### LINKED ISSUE #229: Improve Discussion Page Chatbox and message styling [MODERN DESIGN IMPLEMENTATION]
- Open a dedicated modal on landing page to take input for the user name 
- improve chat box make it more precise 
- changing backgroung image to light so that main focus could be on texts 
- changing theme of the page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #229 
Screenshot 2024-10-25 at 2 14 30 AM
Screenshot 2024-10-25 at 2 16 10 AM

Hey @Harshit7492 please review my PR, also can you please level up if you like the implementation design

### CODE REVIEW

**Comment by shubhagarwal1** [comment]
> Well done @shubhagarwal1. Can you give star to this repo?

Hey @Anuj3553 can you help me with more tasks i can revamp more pages and make them appealing, 
it would be a great approtubity for me

**Comment by Anuj3553** [comment]
> > Well done @shubhagarwal1. Can you give star to this repo?
> 
> Hey @Anuj3553 can you help me with more tasks i can revamp more pages and make them appealing, it would be a great approtubity for me

Yes you can proceed. You can raise your PR.

**Comment by shubhagarwal1** [comment]
> > > Well done @shubhagarwal1. Can you give star to this repo?
> > 
> > 
> > Hey @Anuj3553 can you help me with more tasks i can revamp more pages and make them appealing, it would be a great approtubity for me
> 
> Yes you can proceed. You can raise your PR.

Thankyou so much, can you list me some specific pages, i will start working onthem

**Comment by Anuj3553** [comment]
> > > > Well done @shubhagarwal1. Can you give star to this repo?
> > > 
> > > 
> > > Hey @Anuj3553 can you help me with more tasks i can revamp more pages and make them appealing, it would be a great approtubity for me
> > 
> > 
> > Yes you can proceed. You can raise your PR.
> 
> Thankyou so much, can you list me some specific pages, i will start working onthem

Okay, i will tell you soon. Stay tuned ✌️

**Pull request merged**
