### PR TITLE
Admin backend

### PR DESCRIPTION
**Pull request by ShivanshPlays**
#430 

# PR Justification for Level 3

### Summary
This PR enhances the admin infrastructure by introducing a dedicated table for admin data, backend API routes for streamlined authentication, and comprehensive error handling. These updates focus on improving the admin authentication flow, ensuring a reliable and secure experience. Additionally, minor backend issues were resolved to further stabilize the application.

---

#### 1. Added Table for Admin Infrastructure
   - **Objective**: Establish a separate database table for storing and managing admin-specific data, supporting a structured approach to admin functionalities.
   - **Implementation**:
      - Created a dedicated table for admin data, enabling secure and organized storage of information unique to admins.
      - Ensured unique constraints and data integrity measures are in place, safeguarding against duplicate entries and unauthorized access.

#### 2. Backend API Routes for Admin Authentication
   - **Objective**: Provide a smooth and secure experience for admin users during login and account creation.
   - **Implementation**:
      - Introduced dedicated backend API routes specifically for admin login and account creation, separating them from regular user authentication routes.
      - Integrated logic to handle authentication for admins with added security checks, ensuring that only authorized personnel can access admin functions.
      - Verified that admin-specific sessions and permissions are securely managed, maintaining the integrity of restricted areas in the application.

#### 3. Comprehensive Error Handling
   - **Objective**: Improve the robustness of the admin authentication process by adding detailed error handling for various scenarios.
   - **Implementation**:
      - Incorporated full error handling across all new admin routes, providing specific and actionable feedback for common issues (e.g., invalid credentials, duplicate entries).
      - Used structured error messages to simplify troubleshooting for admins and provide clarity on authentication issues.
      - Logged errors systematically to aid in future debugging and to maintain transparency in the admin authentication process.

#### 4. Resolution of Minor Backend Issues
   - **Objective**: Ensure backend stability by addressing minor issues that were affecting overall functionality.
   - **Implementation**:
      - Reviewed and fixed minor bugs and inconsistencies in the backend, improving the reliability and performance of existing features.
      - Conducted tests to confirm that the backend operates smoothly after implementing these changes, further reinforcing the application’s stability.

---

### Points Justification
This PR meets the **40-45 points** level due to the following contributions:

- **Enhanced Admin Infrastructure**: Established a structured database and API foundation for admin functionalities, laying the groundwork for future expansions.
- **Improved Admin Authentication Flow**: Introduced secure and dedicated backend routes for admin login and account creation, enabling a smooth experience.
- **Comprehensive Error Handling**: Integrated detailed error handling, ensuring clear and actionable feedback for admins.
- **Increased Backend Stability**: Resolved minor backend issues, strengthening the application’s performance and reliability.

---

### Conclusion
This PR provides substantial improvements to the admin experience by adding structured infrastructure, secure authentication routes, and robust error handling. These updates contribute to a more stable and secure application, enhancing both the functionality and maintainability of the backend.

---

# Screenshots/Video (mandatory)

https://github.com/user-attachments/assets/858dbd75-6a81-4ed2-9397-e49ebd2cb513

---

# Checklist:

- [ ] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [ ] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [ ] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Anuj3553** [comment]
Here are some conflicts can you check @ShivanshPlays 

Screenshot_2024_1110_112351

**Comment by ShivanshPlays** [comment]
resolved confilcts...

**Comment by ShivanshPlays** [comment]
@Anuj3553 all conficts has resolved

**Comment by Anuj3553** [comment]
Well done @ShivanshPlays

**Pull request merged**
