### PR TITLE
Added open issue section in our contributor page

### LINKED ISSUE #336: show open issue and what they contribute
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

If anyone wants to contribute, you can show them open issues.

On click contributor profile redirect to new page where you can show what they contribute to this project.

### What problem does this feature solve?

image

i will redesign it according to our website theme !!

### Alternative solutions

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
# Title and Issue number

**Title: #336

**Issue No.: show open issue and what they contribute

Close #336
 

https://github.com/user-attachments/assets/bec1baaf-111d-4d1b-8ca0-1d606b7962df

ADDED OPEN issue section where user can see all the open issue
and can directly contribute from there itself by clicking on that page 

it is beneficial for both admin and developer to look upon the issues 
added pagination for betterment of UI 

clean and clear view of isssue !!

# Checklist:

- [X ] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [ X] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [ X] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Sawan-Kushwah** [comment]
@GUNJESH843 , @Anuj3553 , why this PR doesn't get merge it there any issue with this ?
i can resolve it please reply !!

**Review by GUNJESH843 — COMMENTED** [review]
I think I have recently merged a similar pr which introduced the contributors section in the application.

**Comment by Sawan-Kushwah** [comment]
@GUNJESH843 is there no label on this PR... Just asking??

**Comment by Anuj3553** [comment]
> @GUNJESH843 @Anuj3553 is there no label on this PR why... Just asking??

Solved problem or not @Sawan-Kushwah. Just asking to help you.

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 yes solved thanks for the help ☺️

**Pull request merged**
