### PR TITLE
enchanced the UI of blog page to look for beautiful

### LINKED ISSUE #335: Enhance ui of blog page
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

image

i can make it look better

### What problem does this feature solve?

sample 

image

i willl enhance it ui according to theme

### Alternative solutions

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
**Title: Enhance ui of blog page

**Issue No.: #335 

Close #335 

Screenshot 2024-11-02 171955

image

Make more clean and clear ui of blog page 
now we see the data more clearly and beautifully align to our website theme !!

# Checklist:

- [X ] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [ X] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [ X] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Sawan-Kushwah** [comment]
@GUNJESH843 what about this PR ?
is there improvement needed ?

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, There are some conflicts. Check this -> 

image

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 Resolved all conflicts

**Comment by Anuj3553** [comment]
Well done @Sawan-Kushwah

**Pull request merged**
