### PR TITLE
Add AI and Automation Enhancements

### LINKED ISSUE #153: [Feature Request]: AI and Automation Enhancements
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

To enhance the Bitbox platform's capabilities and provide a smarter, more efficient user experience, we propose integrating AI-powered features and automation tools:

AI-powered Recommendations
Utilize AI to offer personalized project and collaborator recommendations. Recommendations would be based on users' activity, interests, and skill sets, helping them find relevant projects and potential collaborators quickly.

Automated Code Review
Integrate automated code review tools that can analyze submitted code for quality and security vulnerabilities. This feature will assist users in identifying potential issues early and suggest improvements, streamlining the development process.

### What problem does this feature solve?

Increases user engagement through personalized suggestions.
Helps users find suitable projects and team members faster.
Improves code quality and security by catching potential issues automatically.
Saves time for developers by automating repetitive review tasks.

### Alternative solutions

Phase 1: Research and integrate a recommendation engine (e.g., TensorFlow Recommenders, Microsoft Azure ML).
Phase 2: Develop and implement the AI-powered recommendation system for projects and collaborators.
Phase 3: Integrate an automated code review tool (e.g., SonarQube, Codacy) for code quality checks and security analysis.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

### PR DESCRIPTION
**Pull request by sezallagwal**
# Title and Issue number

**Title:** [Feature Request]: AI and Automation Enhancements

**Issue No.:** #153

Close #153

---

# Screenshots/Video (mandatory)

https://github.com/user-attachments/assets/fd989c96-57dc-4de9-9980-e0b13646e11a

---

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [x] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Anuj3553** [comment]
Please give the video of your work as well as here is conflict.

image

**Comment by sezallagwal** [comment]
> Please give the video of your work as well as here is conflict.
 
done :)

**Comment by Anuj3553** [comment]
> > Please give the video of your work as well as here is conflict.
> 
> @Anuj3553 done :)

Please share the video.

**Comment by Anuj3553** [comment]
Well done @sezallagwal

**Pull request merged**
