### PR TITLE
Fix: Responsiveness Issue on Different Screen Sizes

### LINKED ISSUE #175: [Bug]: Responsiveness Issue on Different Screen Sizes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bitbox is experiencing responsiveness issues when viewed on different screen sizes (e.g., mobile devices, tablets, or smaller window resolutions). Certain elements like buttons, text, and images either overlap, break layout, or do not scale properly, leading to a poor user experience on smaller screens.

### Expected behavior

I expected the Bitbox interface to adapt seamlessly to different screen sizes, maintaining proper alignment, visibility, and functionality of all UI elements. The application should adjust layout elements responsively, ensuring that the user interface is fully functional and visually consistent across devices, including mobile, tablet, and desktop.

### Add screenshots (if applicable)

image
image
image

### On which device or platform are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

### PR DESCRIPTION
**Pull request by ghost**
# Title and Issue number

**Title:** Responsiveness Issue on Different Screen Sizes

**Issue No.:** #175

Close  #175

---

# Screenshots/Video (mandatory)

image

---

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [x] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Anuj3553** [comment]
Hyy @amitb0ra, Please check navbar its overflowing.

**Comment by Anuj3553** [comment]
Well done @amitb0ra

**Comment by amitb0ra** [comment]
> Well done @amitb0ra

sorry i got late but i was goint to looki into navbar overflow after my exams.

**Comment by Anuj3553** [comment]
> > Well done @amitb0ra
> 
> sorry i got late but i was going to look into navbar overflow after my exams.

Okk no wories :) @amitb0ra

**Pull request merged**
