### PR TITLE
fixing scroll to top button

### LINKED ISSUE #256: [Bug]: Back to top button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Back to top button is very laggy and slow

### Expected behavior

It should be smooth and fast.

### Add screenshots (if applicable)

https://github.com/user-attachments/assets/dec5a02e-5739-44fb-8922-1605b4e324a6

### On which device or platform are you experiencing this bug?

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

### PR DESCRIPTION
**Pull request by Jordian0**
# [Bug]: Back to top button #256

**Fixed back to top button**

**Issue #256**

Close #256

---

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [X] I have gone through the `contributing.md` file before contributing.

**_Are you contributing under any Open-source programme?_**

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Anuj3553** [comment]
Well done @Jordian0

**Comment by Anuj3553** [comment]
Hyy @Jordian0, You deleted the code and you done nothing. I'm going to complaining this thing to the GSsoC member. Check your work -->

image

---------------------------------------------------------------------------------------------------------------------------------------------

Missing ScrollTop Button -->

image

**Comment by Jordian0** [comment]
@Anuj3553 Hey i'm really sorry, i guess i made the wrong commit. There was more code with it, to make it work as expected.

**Comment by Anuj3553** [comment]
> @Anuj3553 Hey i'm really sorry, i guess i made the wrong commit. There was more code with it, to make it work as expected.

Don't worry i solved this problem.

**Pull request merged**
