### PR TITLE
Added faq page

### LINKED ISSUE #404: faq page revamp
image

redesign the faq page

### PR DESCRIPTION
**Pull request by ShivanshPlays**
#Pull Request Description
#404 Added Faqs page
## Summary

This pull request adds a new FAQ page to the website and includes a link to it in the footer for easy navigation. The FAQ page contains commonly asked questions that provide helpful information for users.

## Changes Made

- **Added a new FAQ page**: A dedicated FAQ page has been created to address common questions about the website, its features, and usage.
- **Updated the footer**: A link to the new FAQ page has been added to the footer section of the website, allowing users to easily access the FAQ page.

## How to Test

1. Navigate to the homepage of the website.
2. Scroll to the footer and locate the **FAQ** link.
3. Click the **FAQ** link to verify that it directs to the new FAQ page.
4. Review the content on the FAQ page to ensure it displays correctly.

## Screenshots

- **Homepage Footer**:image- **FAQ Page**: image

## Additional Information

- The FAQ page is built using the existing design components to ensure consistency with the rest of the website.
- Future updates to the FAQ section can be made directly on the FAQ page.

## Related Issues

- Closes #404  (Add FAQ page feature)

### CODE REVIEW

**Comment by Anuj3553** [comment]
This is looking like blind copy and paste @ShivanshPlays, Please change the content according to our website.

**Comment by ShivanshPlays** [comment]
@Anuj3553 okay, I took sample faqs as reference, I will study the website and curate the faqs accordingly.

**Comment by ShivanshPlays** [comment]
okay will push the changes soon

**Comment by Anuj3553** [comment]
Hyy @ShivanshPlays, Can you create FAQ page better than @Pushpa472 #398 work. I think she makes better FAQ page. You can take reference from it.

**Comment by ShivanshPlays** [comment]
okay will do

**Comment by Pushpa472** [comment]
@Anuj3553 In this issue i should make FQA page

**Comment by ShivanshPlays** [comment]
hey i have redone the work, you can recheck it

**Comment by ShivanshPlays** [comment]
image

image

**Comment by Pushpa472** [comment]
@Anuj3553 now UI design not visible please see it
Screenshot 2024-11-10 125514

**Comment by ShivanshPlays** [comment]
@Pushpa472  @Anuj3553  there was a react version mismatch , having some breaking dependencies, resolved them right now, have a look

https://github.com/user-attachments/assets/4fab0bb7-f823-46dc-91cf-23f487924fd3

**Comment by Pushpa472** [comment]
@ShivanshPlays which dependencies, I checked many times, and there is a lost of error in the console i solve then also not work 
if you known this plz tell me.. i am also working on frontend

**Comment by ShivanshPlays** [comment]
@Anuj3553 please check

**Comment by ShivanshPlays** [comment]
@Anuj3553 conflict resolved

**Comment by ShivanshPlays** [comment]
@Anuj3553  please merge

**Comment by ShivanshPlays** [comment]
@Anuj3553  @Pushpa472 hey can you review it and merge the branch

**Pull request merged**
