### PR TITLE
Added backend and frontend for read more page of blog

### LINKED ISSUE #327: [Feature Request]: Create read more page for blog data fetched by backend
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

image

### What problem does this feature solve?

when blog are too big it is not good to show all content on blog page 
if blog is big then turn cate it and there should be a read more page where we show full content of blog !!
this data has been fetched by BACKEND 

### Alternative solutions

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
**Title: Create read more page for blog data fetched by backend

**Issue No.: #327 

Close #327 
 

https://github.com/user-attachments/assets/ef417087-ab45-4ed0-984e-54e55c7bfe3d

 
 Added fully functional read more blog page 
 fetch data from backend 
 render the blog data according to id 
 Beautiful ui of read more page
 # can i get level 3 for it as calling the data by id render that on beautiful ui of blog page !!
 

# Checklist:

- [X ] I have mentioned the issue number in my Pull Request.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [X ] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [X ] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, There is some conflicts. 

image

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 hey can i get level 3 for this PR?

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 is there something wrong with this PR why it doesn't get merge

**Comment by Anuj3553** [comment]
Well done @Sawan-Kushwah

**Pull request merged**
