### PR TITLE
Add a pop up dialog box for subscribing to newsletter done ! #265

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #265
Add a pop up dialog box for subscribing to newsletter done properly -

Screenshot 2024-10-28 233204
Screenshot 2024-10-28 235022

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [x] I have gone through the `contributing.md` file before contributing.

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Anuj3553** [comment]
> @Anuj3553 done, please merge my PR with level 3, If you check other projects, they are also giving level 3 for this.. i add this new feature, You can check my code also...
> 
> Thank You 🙏🏻

I can only give level2 for this.

**Comment by Anuj3553** [comment]
Well done @Subhajit-2023-44

**Comment by Subhajit-2023-44** [comment]
> > @Anuj3553 done, please merge my PR with level 3, If you check other projects, they are also giving level 3 for this.. i add this new feature, You can check my code also...
> > Thank You 🙏🏻
> 
> I can only give level2 for this.

Okay, Thank You

**Comment by Subhajit-2023-44** [comment]
> > @Anuj3553 done, please merge my PR with level 3, If you check other projects, they are also giving level 3 for this.. i add this new feature, You can check my code also...
> > Thank You 🙏🏻
> 
> I can only give level2 for this.

@Anuj3553 okay 😢Thank You

I would be very grateful if you could give me level 3 for this.. because If you check other projects, they are also giving level 3 for this...

Screenshot 2024-10-28 204307
Screenshot 2024-10-28 204225

**Comment by Anuj3553** [comment]
> Hello, PR Add new feature - #265 Add a pop up dialog box for subscribing to newsletter done properly -
> 
> Screenshot 2024-10-28 233204 Screenshot 2024-10-28 235022
> 
> # Checklist:
> * [x]  I have mentioned the issue number in my Pull Request.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
> * [x]  I have gone through the `contributing.md` file before contributing.
> 
> * [x]  I'm a GSSOC-EXT contributor
> * [x]  I'm a HACKTOBERFEST contributor

When i can saw this popup.

**Comment by Anuj3553** [comment]
Please send the video of your task.

**Pull request merged**
